name: CI/CD
on:
  push:
    branches: [ dev ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /www/wwwroot/sxzx
          git remote add origin git@github.com:2021sxzx/2021sxzx-server.git
          git checkout -b dev
          git pull
          export NODE_HOME=/www/server/nvm/versions/node/v12.19.1
          export PATH=$PATH:$NODE_HOME/bin
          npm install
          pm2 delete 0
          pm2 start npm --name sxzx -- run pro